### ISSUE TITLE
the element is not returned and chaining does not work

### ISSUE THREAD

**Issue by ejulianova** [john-terenzio/jQuery-Hover-Delay#1]
Both of these result in a script error:

$('#myElement').hover(function () {
 console.log('mouseenter');
}, function () {
 console.log('mouseleave');
}).click(); 

$('#myElement').hover(function () {
 console.log('mouseenter');
}, function () {
 console.log('mouseleave');
}, 100).click();

**Comment by john-terenzio** [comment]
Should be fixed now. Thanks.

**Comment by ejulianova** [comment]
that was fast :) thanks
